version: '3.8'

services:
  telethon-bot:
    build: .
    image_name: telethon_bot
    container_name: telethon_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
